### ISSUE TITLE
NPE On Android 4.0 during connect

### ISSUE THREAD

**Issue by GoogleCodeExporter** [peteaky/android-xbmcremote#584]
```
What steps will reproduce the problem?
1. Re-Connect
2. Connect in den mainwindows
3.

What is the expected output? What do you see instead?

Expect to connect - NullPointerException

What version of XBMC Remote are you using?

Newest from the market

Which Android device are you using (and which ROM, if custom)?

Nexus S with Drewgarren Android 4.0 Stock

Which XBMC revision are you running and on which platform?




Please provide any additional information below.

```

Original issue reported on code.google.com by `ChillKro...@gmail.com` on 6 Dec 2011 at 7:03

**Comment by GoogleCodeExporter** [comment]
```
Sorry, iam using the newest XBMC on Ubuntu 10.04 
```

Original comment by `ChillKro...@gmail.com` on 6 Dec 2011 at 7:20

**Comment by GoogleCodeExporter** [comment]
```
Same problem here on a Galaxy Nexus (4.0.1). After setting up a host using the 
same settings as on my other devices I get NPE when trying to connect.
```

Original comment by `jensh...@gmail.com` on 16 Dec 2011 at 6:32

**Comment by GoogleCodeExporter** [comment]
```
Logcat output on Samsung Galaxy Nexus :

W/System.err( 1243): java.io.EOFException
W/System.err( 1243): at libcore.io.Streams.readAsciiLine(Streams.java:203)
W/System.err( 1243): at 
libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:547)
W/System.err( 1243): at 
libcore.net.http.HttpEngine.readResponse(HttpEngine.java:787)
W/System.err( 1243): at 
libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:27
4)
W/System.err( 1243): at 
libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java
:168)
W/System.err( 1243): at org.xbmc.httpapi.Connection.query(Connection.java:278)
W/System.err( 1243): at 
org.xbmc.httpapi.Connection.assertBoolean(Connection.java:357)
W/System.err( 1243): at 
org.xbmc.httpapi.client.ControlClient.setResponseFormat(ControlClient.java:406)
W/System.err( 1243): at 
org.xbmc.android.util.ClientFactory$1.run(ClientFactory.java:171)

Or :
W/System.err( 1263): java.io.EOFException
W/System.err( 1263): at libcore.io.Streams.readAsciiLine(Streams.java:203)
W/System.err( 1263): at 
libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:547)
W/System.err( 1263): at 
libcore.net.http.HttpEngine.readResponse(HttpEngine.java:787)
W/System.err( 1263): at 
libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:27
4)
W/System.err( 1263): at 
libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java
:168)
W/System.err( 1263): at org.xbmc.httpapi.Connection.query(Connection.java:278)
W/System.err( 1263): at 
org.xbmc.httpapi.Connection.getString(Connection.java:313)
W/System.err( 1263): at 
org.xbmc.httpapi.client.InfoClient.getSystemInfo(InfoClient.java:126)
W/System.err( 1263): at 
org.xbmc.android.remote.business.InfoManager$1.doRun(InfoManager.java:51)
W/System.err( 1263): at 
org.xbmc.android.remote.business.Command.run(Command.java:40)
W/System.err( 1263): at android.os.Handler.handleCallback(Handler.java:605)
W/System.err( 1263): at android.os.Handler.dispatchMessage(Handler.java:92)
W/System.err( 1263): at android.os.Looper.loop(Looper.java:137)
W/System.err( 1263): at 
org.xbmc.android.remote.business.ManagerThread.run(ManagerThread.java:78)
```

Original comment by `faugusz...@gmail.com` on 16 Dec 2011 at 8:08
