### ISSUE TITLE
ice cream sandwich support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [peteaky/android-xbmcremote#586]
```

Clean installation gives a nullpointer exeption
```

Original issue reported on code.google.com by `rikvanma...@gmail.com` on 11 Dec 2011 at 9:53
- Merged into: #581

**Comment by GoogleCodeExporter** [comment]
```
Used with a Desire HD with ICS rom on it.
SO it's not a Nexus S generic error
```

Original comment by `rikvanma...@gmail.com` on 12 Dec 2011 at 1:03

**Comment by GoogleCodeExporter** [comment]
```
I have the same error on the new Samsung Galaxy Nexus with Android 4.0.1
```

Original comment by `christia...@gmail.com` on 14 Dec 2011 at 12:24

**Comment by GoogleCodeExporter** [comment]
```
Same issue here, trying to connect to current OS X XBMC on Snow Leopard.

logcat:
I/ClientFactory( 3199): VERSION = 10.1 Git:e9e9099
I/ClientFactory( 3199): Found XBMC at Git commit e9e9099!
I/Connection( 3199): 
http://192.168.99.8:8080/xbmcCmds/xbmcHttp?command=GetSystemInfo(120)
I/Connection( 3199): 
http://192.168.99.8:8080/xbmcCmds/xbmcHttp?command=SetResponseFormat(WebHeader;t
rue;WebFooter;true;Header; ;Footer; ;OpenTag;<li>;CloseTag;
I/Connection( 3199): ;CloseFinalTag;false)
W/System.err( 3199): java.io.EOFException
W/System.err( 3199):    at libcore.io.Streams.readAsciiLine(Streams.java:203)
W/System.err( 3199):    at 
libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:547)
W/System.err( 3199):    at 
libcore.net.http.HttpEngine.readResponse(HttpEngine.java:787)
W/System.err( 3199):    at 
libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:27
4)
W/System.err( 3199):    at 
libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java
:168)
W/System.err( 3199):    at org.xbmc.httpapi.Connection.query(Connection.java:278)
W/System.err( 3199):    at 
org.xbmc.httpapi.Connection.getString(Connection.java:313)
W/System.err( 3199):    at 
org.xbmc.httpapi.client.InfoClient.getSystemInfo(InfoClient.java:126)
W/System.err( 3199):    at 
org.xbmc.android.remote.business.InfoManager$1.doRun(InfoManager.java:51)
W/System.err( 3199):    at 
org.xbmc.android.remote.business.Command.run(Command.java:40)
W/System.err( 3199):    at android.os.Handler.handleCallback(Handler.java:605)
W/System.err( 3199):    at android.os.Handler.dispatchMessage(Handler.java:92)
W/System.err( 3199):    at android.os.Looper.loop(Looper.java:137)
W/System.err( 3199):    at 
org.xbmc.android.remote.business.ManagerThread.run(ManagerThread.java:78)
W/System.err( 3199): java.lang.NullPointerException
W/System.err( 3199):    at 
org.xbmc.android.remote.presentation.controller.AbstractController.onError(Abstr
actController.java:237)
W/System.err( 3199):    at 
org.xbmc.android.remote.business.AbstractManager.onError(AbstractManager.java:29
3)
W/System.err( 3199):    at org.xbmc.httpapi.Connection.query(Connection.java:298)
W/System.err( 3199):    at 
org.xbmc.httpapi.Connection.getString(Connection.java:313)
W/System.err( 3199):    at 
org.xbmc.httpapi.client.InfoClient.getSystemInfo(InfoClient.java:126)
W/System.err( 3199):    at 
org.xbmc.android.remote.business.InfoManager$1.doRun(InfoManager.java:51)
W/System.err( 3199):    at 
org.xbmc.android.remote.business.Command.run(Command.java:40)
W/System.err( 3199):    at android.os.Handler.handleCallback(Handler.java:605)
W/System.err( 3199):    at android.os.Handler.dispatchMessage(Handler.java:92)
W/System.err( 3199):    at android.os.Looper.loop(Looper.java:137)
W/System.err( 3199):    at 
org.xbmc.android.remote.business.ManagerThread.run(ManagerThread.java:78)
I/Connection( 3199): 
http://192.168.99.8:8080/xbmcCmds/xbmcHttp?command=SetResponseFormat(OpenRecordS
et; ;CloseRecordSet; ;OpenRecord; ;CloseRecord; 
;OpenField;<field>;CloseField;</field>)
W/System.err( 3199): java.io.EOFException
W/System.err( 3199):    at libcore.io.Streams.readAsciiLine(Streams.java:203)
W/System.err( 3199):    at 
libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:547)
W/System.err( 3199):    at 
libcore.net.http.HttpEngine.readResponse(HttpEngine.java:787)
W/System.err( 3199):    at 
libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:27
4)
W/System.err( 3199):    at 
libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java
:168)
W/System.err( 3199):    at org.xbmc.httpapi.Connection.query(Connection.java:278)
W/System.err( 3199):    at 
org.xbmc.httpapi.Connection.assertBoolean(Connection.java:357)
W/System.err( 3199):    at 
org.xbmc.httpapi.client.ControlClient.setResponseFormat(ControlClient.java:406)
W/System.err( 3199):    at 
org.xbmc.android.util.ClientFactory$1.run(ClientFactory.java:171)

```

Original comment by `a...@9600.org` on 18 Dec 2011 at 1:01

**Comment by GoogleCodeExporter** [comment]
```
I just got 4 as well.
I verify the Null Pointer Exception.

But the remote control does work.
I an only view the controls but clicking on them it will behave as expected.

```

Original comment by `stevoo82` on 18 Dec 2011 at 1:06

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Above confirmed on plain unlocked Nexus S for Tmobile (i9020T) with new ICS 
upgrade and XMBC on both windows 7 and XP. Though you still get nullpointer 
exceptions, remote control portion of app can be used in some cases. Sometimes 
you get stuck in force close loop as well. None of the library functionality 
works on ICS. Worked great with Gingerbread.
```

Original comment by `gregs...@gmail.com` on 26 Dec 2011 at 7:57

**Comment by GoogleCodeExporter** [comment]
Original comment by `phree...@gmail.com` on 27 Dec 2011 at 3:16
- Changed state: **Duplicate**

**Comment by GoogleCodeExporter** [comment]
```
Same problem with CyanogenMod 9 (ICS) on Samsung Galaxy S2.
```

Original comment by `batzk...@gmail.com` on 13 Sep 2012 at 2:51

**Comment by GoogleCodeExporter** [comment]
```
Same problem with Galaxy S2 android 4.0.4
```

Original comment by `sebastia...@gmail.com` on 23 Mar 2013 at 11:18
