### ISSUE TITLE
XBMC Remtoe doesn't work on Android 4.0.3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [peteaky/android-xbmcremote#588]
```
What steps will reproduce the problem?
1. Open XBMC remote or try to make it connect to the xbmc host

What is the expected output? What do you see instead?
NullPointerException upon trying to connect to get the TV Shows, Movies, etc. 
But sms notification works

What version of XBMC Remote are you using?
v0.8.7-beta1


Which Android device are you using (and which ROM, if custom)?
Nexus S with android 4.0.3


Which XBMC revision are you running and on which platform?
10.1

```

Original issue reported on code.google.com by `mello...@gmail.com` on 17 Dec 2011 at 3:20
- Merged into: #581

**Comment by GoogleCodeExporter** [comment]
```
I have the same problem here. I have a Samsung Galaxy S I9000 with android 
4.0.3 by onecosmic. 
```

Original comment by `pascalwo...@gmail.com` on 26 Dec 2011 at 1:35

**Comment by GoogleCodeExporter** [comment]
```
same here on a Samsung Nexus S and Android 4.0.3
```

Original comment by `norbert....@gmail.com` on 28 Dec 2011 at 8:57

**Comment by GoogleCodeExporter** [comment]
```
HTC Sensation with ICS based InsertCoin here. XBMC Remote installed from market.
Trying to connect to server:
$ grep 6073 ~/tmp/xbmc-logcat.txt
I/ActivityManager(  257): Start proc org.xbmc.android.remote for activity 
org.xbmc.android.remote/.presentation.activity.HomeActivity: pid=6073 uid=10164 
gids={3003, 1015}
D/memalloc( 6073): map_buffer: Successfully mapped 245760 bytes
D/memalloc( 6073): map_buffer: Successfully mapped 245760 bytes
V/Performance( 6073): 
>>org.xbmc.android.remote.presentation.activity.HomeActivity@40dc34f0 
performSaveInstanceState
V/Performance( 6073): 
<<org.xbmc.android.remote.presentation.activity.HomeActivity@40dc34f0 
performSaveInstanceState, 1ms
V/Performance( 6073): 
>>org.xbmc.android.remote.presentation.activity.HomeActivity@40dc34f0 
performPause
V/Performance( 6073): 
<<org.xbmc.android.remote.presentation.activity.HomeActivity@40dc34f0 
performPause, 0ms
D/dalvikvm( 6073): GC_CONCURRENT freed 250K, 10% free 3240K/3591K, paused 
2ms+28ms
V/Performance( 6073): 
>>org.xbmc.android.remote.presentation.activity.HomeActivity@40dc34f0 onResume
V/Performance( 6073): 
<<org.xbmc.android.remote.presentation.activity.HomeActivity@40dc34f0 onResume, 
0ms
D/Command ( 6073): Running command counter: 1
D/WifiHelper( 6073): WIFI_STATE_CONNECTED to bananacisco
I/Connection( 6073): 
http://192.168.231.222:8080/xbmcCmds/xbmcHttp?command=GetSystemInfo(120)
V/Performance( 6073): 
>>org.xbmc.android.remote.presentation.activity.HomeActivity@40dc34f0 
performSaveInstanceState
V/Performance( 6073): 
<<org.xbmc.android.remote.presentation.activity.HomeActivity@40dc34f0 
performSaveInstanceState, 0ms
V/Performance( 6073): 
>>org.xbmc.android.remote.presentation.activity.HomeActivity@40dc34f0 
performPause
V/Performance( 6073): 
<<org.xbmc.android.remote.presentation.activity.HomeActivity@40dc34f0 
performPause, 0ms
I/ClientFactory( 6073): VERSION = 
I/Connection( 6073): 
http://192.168.231.222:8080/xbmcCmds/xbmcHttp?command=GetSystemInfo(120)
I/Connection( 6073): 
http://192.168.231.222:8080/xbmcCmds/xbmcHttp?command=SetResponseFormat(WebHeade
r;true;WebFooter;true;Header; ;Footer; ;OpenTag;<li>;CloseTag;
I/Connection( 6073): ;CloseFinalTag;false)
I/org.xbmc.android.remote.business.InfoManager( 6073): *** getSystemInfo: 2572ms
W/AbstractManager( 6073): *** ignoring onFinish, controller is null.
V/Performance( 6073): 
>>org.xbmc.android.remote.presentation.activity.HomeActivity@40dc34f0 onResume
V/Performance( 6073): 
<<org.xbmc.android.remote.presentation.activity.HomeActivity@40dc34f0 onResume, 
0ms
D/Command ( 6073): Running command counter: 1
D/WifiHelper( 6073): WIFI_STATE_CONNECTED to bananacisco
I/Connection( 6073): 
http://192.168.231.222:8080/xbmcCmds/xbmcHttp?command=GetSystemInfo(120)
W/System.err( 6073): java.io.EOFException
W/System.err( 6073):    at libcore.io.Streams.readAsciiLine(Streams.java:203)
W/System.err( 6073):    at 
libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:547)
W/System.err( 6073):    at 
libcore.net.http.HttpEngine.readResponse(HttpEngine.java:787)
W/System.err( 6073):    at 
libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:27
4)
W/System.err( 6073):    at 
libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java
:168)
W/System.err( 6073):    at org.xbmc.httpapi.Connection.query(Connection.java:278)
W/System.err( 6073):    at 
org.xbmc.httpapi.Connection.getString(Connection.java:313)
W/System.err( 6073):    at 
org.xbmc.httpapi.client.InfoClient.getSystemInfo(InfoClient.java:126)
W/System.err( 6073):    at 
org.xbmc.android.util.ClientFactory.probeQueryApiType(ClientFactory.java:216)
W/System.err( 6073):    at 
org.xbmc.android.util.ClientFactory.getInfoClient(ClientFactory.java:68)
W/System.err( 6073):    at 
org.xbmc.android.remote.business.AbstractManager.info(AbstractManager.java:107)
W/System.err( 6073):    at 
org.xbmc.android.remote.business.InfoManager$1.doRun(InfoManager.java:51)
W/System.err( 6073):    at 
org.xbmc.android.remote.business.Command.run(Command.java:40)
W/System.err( 6073):    at android.os.Handler.handleCallback(Handler.java:605)
W/System.err( 6073):    at android.os.Handler.dispatchMessage(Handler.java:92)
W/System.err( 6073):    at android.os.Looper.loop(Looper.java:154)
W/System.err( 6073):    at 
org.xbmc.android.remote.business.ManagerThread.run(ManagerThread.java:78)
W/System.err( 6073): java.lang.NullPointerException
W/System.err( 6073):    at 
org.xbmc.android.remote.presentation.controller.AbstractController.onError(Abstr
actController.java:237)
W/System.err( 6073):    at 
org.xbmc.android.remote.business.AbstractManager.onError(AbstractManager.java:29
3)
W/System.err( 6073):    at org.xbmc.httpapi.Connection.query(Connection.java:298)
W/System.err( 6073):    at 
org.xbmc.httpapi.Connection.getString(Connection.java:313)
W/System.err( 6073):    at 
org.xbmc.httpapi.client.InfoClient.getSystemInfo(InfoClient.java:126)
W/System.err( 6073):    at 
org.xbmc.android.util.ClientFactory.probeQueryApiType(ClientFactory.java:216)
W/System.err( 6073):    at 
org.xbmc.android.util.ClientFactory.getInfoClient(ClientFactory.java:68)
W/System.err( 6073):    at 
org.xbmc.android.remote.business.AbstractManager.info(AbstractManager.java:107)
W/System.err( 6073):    at 
org.xbmc.android.remote.business.InfoManager$1.doRun(InfoManager.java:51)
W/System.err( 6073):    at 
org.xbmc.android.remote.business.Command.run(Command.java:40)
W/System.err( 6073):    at android.os.Handler.handleCallback(Handler.java:605)
W/System.err( 6073):    at android.os.Handler.dispatchMessage(Handler.java:92)
W/System.err( 6073):    at android.os.Looper.loop(Looper.java:154)
W/System.err( 6073):    at 
org.xbmc.android.remote.business.ManagerThread.run(ManagerThread.java:78)
D/memalloc( 6073): map_buffer: Successfully mapped 245760 bytes
D/memalloc( 6073): map_buffer: Successfully mapped 245760 bytes
I/ClientFactory( 6073): Resetting client to 192.168.231.222
W/ClientFactory( 6073): Not updating event client's host because no instance is 
set yet.

Which is absolutely correct since XBMC sends a reset packet right after the GET 
from remote:
11:54:40.719282 IP 192.168.244.120.40475 > 192.168.231.222.8080: Flags [P.], 
seq 244:522, ack 123, win 8177, options [nop,nop,TS val 6680908 ecr 152687698], 
length 278
GET /xbmcCmds/xbmcHttp?command=GetSystemInfo(120) HTTP/1.1
Authorization: Basic eGJtYzp4Ym1j
User-Agent: Dalvik/1.6.0 (Linux; U; Android 4.0.1; HTC Sensation XE with Beats 
Audio Z715e Build/ITL41D)
Host: 192.168.231.222:8080
Connection: Keep-Alive
Accept-Encoding: gzip


11:54:40.719296 IP 192.168.231.222.8080 > 192.168.244.120.40475: Flags [R], seq 
2960103219, win 0, length 0

The same GET from browser or GB device works as expected:
12:00:28.726719 IP 192.168.244.126.47543 > 192.168.231.222.8080: Flags [P.], 
seq 1:253, ack 1, win 2920, options [nop,nop,TS val 29942 ecr 152774801], 
length 252
GET /xbmcCmds/xbmcHttp?command=GetSystemInfo(120) HTTP/1.1
User-Agent: Dalvik/1.4.0 (Linux; U; Android 2.3.3; GT-P1000 Build/GINGERBREAD)
Host: 192.168.231.222:8080
Connection: Keep-Alive
Accept-Encoding: gzip
Authorization: Basic eGJtYzp4Ym1j


12:00:28.726733 IP 192.168.231.222.8080 > 192.168.244.126.47543: Flags [.], ack 
253, win 108, options [nop,nop,TS val 152774864 ecr 29942], length 0
12:00:28.750040 IP 192.168.231.222.8080 > 192.168.244.126.47543: Flags [P.], 
seq 1:113, ack 253, win 108, options [nop,nop,TS val 152774870 ecr 29942], 
length 112
HTTP/1.1 200 OK
Content-Length: 36
Date: Thu, 29 Dec 2011 11:00:28 GMT

<html>
<li>10.1 Git:Unknown
</html>


Can't enable debug on xbmc right now.
```

Original comment by `mtabol...@gmail.com` on 29 Dec 2011 at 11:03

**Comment by GoogleCodeExporter** [comment]
```
Last update from Android Market fixed the issues
```

Original comment by `mello...@gmail.com` on 3 Jan 2012 at 9:32

**Comment by GoogleCodeExporter** [comment]
Original comment by `phree...@gmail.com` on 4 Jan 2012 at 8:43
- Changed state: **Duplicate**

**Comment by GoogleCodeExporter** [comment]
```
same here with the HTC Sensation running virtuous aosap senseless 4.0.3
```

Original comment by `marlo.pl...@gmail.com` on 30 Jan 2012 at 10:31
